---
- name: install dependencies for poky installer
  apt:
    name:
      - build-essential
      - bzip2
      - file
      - tar
    cache_valid_time: 3600
    update_cache: yes

- name: copy poky installer
  copy:
    src: "{{ poky_installer_file }}"
    dest: "/tmp/{{ poky_installer_file }}"
    mode: 0750
  register: poky_copy
  ignore_errors: yes
  tags: [poky]

- name: execute poky installer
  command: "/tmp/{{ poky_installer_file }} -y -d '{{ poky_dest }}'"
  args:
    creates: "{{ poky_dest }}"
  when: poky_copy.failed == False
  tags: [poky]

- name: change owner/group to jenkins user
  file:
    path: "{{ poky_dest }}"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_user }}"
    recurse: yes
  when: poky_copy.failed == False
  tags: [poky]

- name: remove poky installer
  file:
    path: "/tmp/{{ poky_installer_file }}"
    state: absent
  when: poky_copy.failed == False
  tags: [poky]

- name: "Please download {{ poky_installer_file }} to your ansible directory to allow ansible to install poky"
  debug:
    msg: "Ansible can not find or copy {{ poky_installer_file }}"
  when: poky_copy.failed == True
  tags: [poky]
