---
- name: setup osmo-gsm-tester apu
  hosts: gsm_tester
  user: root
  tasks:
    - name: install common utilities
      apt:
        name:
          - vim
          - tmux
          - screen
          - ca-certificates
          - wget
          - curl
        cache_valid_time: 3600
        update_cache: yes
    - name: deploy osmo-ci to home directory
      become: yes
      become_user: "jenkins"
      git:
        repo: "https://gerrit.osmocom.org/osmo-ci"
        dest: "/home/jenkins/osmo-ci"
  roles:
    - name: gsm-tester
      tags:
        - gsm-tester

    - name: gsm-tester-modems
      tags:
        - gsm-tester
        - gsm-tester-modems

    - name: gsm-tester-bts
      tags:
        - gsm-tester
        - gsm-tester-bts

    - name: gsm-tester-network
      bts_interface: enp2s0
      tags:
        - gsm-tester

    - name: osmocom-jenkins-slave
      jenkins_user: jenkins
      generic_slave: false
      tags:
        - jenkins-slave

    - name: docker
      jenkins_user: jenkins
      tags:
        - docker

    - name: udhcpd
      udhcpd_router: 10.42.42.1
      udhcpd_range_start: 10.42.42.230
      udhcpd_range_end: 10.42.42.235
      udhcpd_subnet: 255.255.255.0
      udhcpd_dns: 8.8.8.8
      udhcpd_interface: enp2s0
      # udhcpd_static_leases is set via host_vars/*
